print("My Daily Routine")
print("I wake up")
print("I brush my teeth")
print("I eat breakfast")
print("I play with my neighbour")
print("I eat lunch")
print("I do homework")
print("I do coding")
print("I eat dinner")
print("I sleep")